### ISSUE TITLE
Метрополитен_1

### ISSUE THREAD

**Issue by besogonn** [besogonn/Homework#1]
@vdetstvepil

**Comment by vdetstvepil** [comment]
**Файл Station.cs**
- 26 строку следует убрать, иначе будет присвоение ссылок.
- 31 строка. О какой переменной transfers идет речь? Я так полагаю, что ты хочешь скопипастить элементы из одного списка в другой. Но ты копипастишь элементы из входного списка в него же. Подсказка: где-то нужно вставить слово this.

**Comment by vdetstvepil** [comment]
Поправишь и зачту.

**Comment by besogonn** [comment]
Ок

**Comment by besogonn** [comment]
А разве 26 строка как раз и помогала избегать проблемы на 31 строке? Или я что-то не понял... Можно дотянуть этот вопрос до вторника?

**Comment by vdetstvepil** [comment]
Ну так сначала надо transfers инициализировать новым списком, а потому уже через цикл добавлять элементы из входного списка в текущий.
